# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["AUTO-BUILD"]
  pull_request:
    branches: ["AUTO-BUILD"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_PORT: ${{ secrets.PORT }}
          ENV_MONGO_URI: ${{ secrets.MONGO_URI }}
          ENV_EXPIRES_IN: ${{ secrets.EXPIRES_IN }}
          ENV_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm start
          kill -15 -1
          kill -9 -1
