# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["AUTO-BUILD"]
  pull_request:
    branches: ["AUTO-BUILD"]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create .env file
        run: |
          echo PORT = 8000 MONGO_URI = rehbbher EXPIRES_IN = 40 JWT_SECRET_KEY = bdfsbafbdfbdfeb > .env

      - run: npm ci
      - run: npm start
